tax = { "Metaphysics and Epistemology":{
	"Epistemology":{
		"Epistemological Sources":{
			"The A Priori":{
				"Apriority and Necessity":{},
				"Apriority in Mathematics":{},
				"Conceptual Analysis":{},
				"Modal Rationalism":{},
				"Moral Rationalism":{},
				"Rationalism":{},
				"The A Priori, Misc":{},
				"The Synthetic A Priori":{},
				"Theories of the A Priori":{}},
			"Intuition":{
				"Epistemology of Intuition":{},
				"Intuition, Misc":{},
				"Linguistic Intuition":{},
				"Mathematical Intuition":{},
				"Modal Intuition":{},
				"Moral Intuitionism":{},
				"The Nature of Intuition":{}},
			"Memory":{},
			"Perceptual Knowledge":{},
			"Reasoning":{
				"Abductive Reasoning":{},
				"Argument":{},
				"Critical Reasoning":{},
				"Deductive Reasoning":{},
				"Fallacies":{},
				"Induction":{},
				"Inference":{}},
			"Self-Knowledge":{},
			"Testimony":{
				"Epistemology of Testimony":{},
				"Testimony, Misc":{},
				"The Nature of Testimony":{}}},
		"Epistemological States and Properties":{
			"Basing":{},
			"Belief":{},
			"Defeat":{},
			"Entitlement":{},
			"Evidence":{
				"Evidence and Knowledge":{},
				"Evidentialism":{},
				"Perceptual Knowledge":{},
				"The Problem of Old Evidence":{},
				"Underdetermination of Theory by Data":{},
				"Evidence, Misc":{}},
			"Ignorance":{},
			"Justification":{
				"Coherentism":{},
				"Dogmatism":{},
				"Epistemic Internalism and Externalism":{},
				"Epistemic Regress":{},
				"Evidentialism":{},
				"Foundationalism":{},
				"Infinitism":{},
				"Justification, Misc":{},
				"Moral Justification":{},
				"Perceptual Justification":{},
				"Reliabilism about Justification":{}},
			"Knowledge":{},
			"Rationality":{
				"Delusions":{},
				"Irrationality":{},
				"Moral Rationality":{},
				"Rational Requirements":{},
				"Rationality, Misc":{},
				"Rationality and Cognitive Science":{},
				"Reasons and Rationality":{}},
			"Reasons":{},
			"Understanding":{},
			"Warrant":{},
			"Wisdom":{},
			"Epistemological States and Properties, Misc":{}},
		"Epistemological Theories":{
			"Coherentism":{
				"Coherentism, Misc":{},
				"Epistemic Regress":{},
				"Foundationalism and Coherentism":{}},
			"Dogmatism":{
				"Dogmatism about Perception":{},
				"Dogmatism, Misc":{},
				"Dogmatist and Moorean Replies to Skepticism":{}},
			"Epistemic Contextualism":{
				"Contextualist Replies to Skepticism":{},
				"Epistemic Contextualism and Invariantism":{},
				"Epistemic Contextualism and Relativism":{},
				"Epistemic Contextualism, Misc":{},
				"Epistemic Contrastivism":{}},
			"Epistemic Internalism and Externalism":{},
			"Epistemic Relativism":{
				"Epistemic Contextualism and Relativism":{},
				"Epistemic Relativism, Misc":{}},
			"Empiricism":{},
			"Evidentialism":{},
			"Foundationalism":{
				"Foundationalism and Coherentism":{},
				"Foundationalism, Misc":{},
				"Sense-Datum Theories of Perception":{},
				"The Given":{}},
			"Infinitism":{},
			"Rationalism":{},
			"Reliabilism":{
				"Reliabilism about Knowledge":{},
				"Reliabilism about Justification":{},
				"Reliabilism, Misc":{},
				"The Problem of Easy Knowledge":{},
				"The Generality Problem for Reliabilism":{}},
			"Virtue Epistemology":{},
			"Epistemological Theories, Misc":{}},
		"Epistemology of Specific Domains":{
			"Epistemology of Logic":{},
			"Epistemology of Mathematics":{},
			"Epistemology of Philosophy":{},
			"Epistemology of Religion":{},
			"Epistemology of Specific Domains, Misc":{},
			"Knowledge of Consciousness":{},
			"Knowledge of Language":{},
			"Modal Epistemology":{},
			"Moral Epistemology":{},
			"The Problem of Other Minds":{},
			"Self-Knowledge":{}},
		"Epistemology, Misc":{
			"Epistemic Luck":{},
			"Epistemic Paradoxes":{},
			"Epistemic Possibility":{},
			"Feminist Epistemology":{},
			"Evolutionary Epistemology":{},
			"Metaepistemology":{},
			"Naturalized Epistemology":{}},
		"Epistemic Normativity":{
			"Doxastic Voluntarism":{},
			"Epistemic Normativity, Misc":{},
			"Epistemic Norms":{},
			"Epistemic Value":{},
			"Epistemic Virtues":{},
			"Ethics of Belief":{}},
		"Formal Epistemology":{
			"Belief Revision":{
				"AGM Belief Revision Theory":{},
				"Belief Revision, Misc":{},
				"Nonmonotonic Logic":{},
				"Ranking Functions":{}},
			"Causal Reasoning":{
				"Causal Modeling":{},
				"Causal Reasoning, Misc":{},
				"Common Cause Principles":{}},
			"Confirmation and Induction":{},
			"Epistemic Logics":{},
			"Formal Social Epistemology":{
				"Common Knowledge":{},
				"Formal Social Epistemology, Misc":{},
				"Judgment Aggregation":{},
				"Peer Disagreement":{}},
			"Formal Epistemology, Misc":{},
			"Probabilistic Reasoning":{}},
		"Knowledge":{
			"Defining Knowledge":{
				"Defining Knowledge, Misc":{},
				"Primitivism about Knowledge":{},
				"The Gettier Problem":{}},
			"Varieties of Knowledge":{
				"Knowledge by Acquaintance":{},
				"Knowledge How":{},
				"Knowledge-Wh":{},
				"Varieties of Knowledge, Misc":{}},
			"Theories of Knowledge":{
				"Causal Theory of Knowledge":{},
				"Epistemic Contextualism":{},
				"Epistemic Relativism":{},
				"Primitivism about Knowledge":{},
				"Reliabilism about Knowledge":{},
				"Theories of Knowledge, Misc":{}},
			"Principles of Knowledge":{
				"Closure":{},
				"Infallibility":{},
				"Knowability":{},
				"The KK Principle":{},
				"Luminosity":{},
				"Safety and Sensitivity":{},
				"Principles of Knowledge, Misc":{}},
			"Knowledge, Misc":{
				"Knowledge, Misc":{},
				"The Problem of Easy Knowledge":{}}},
		"Skepticism":{
			"Varieties of Skepticism":{
				"Are We in A Simulation?":{},
				"Brains in Vats":{},
				"Cartesian Skepticism":{},
				"Dreams and Skepticism":{},
				"Inductive Skepticism":{},
				"Metaphilosophical Skepticism":{},
				"Modal Skepticism":{},
				"Moral Skepticism":{},
				"Perception and Skepticism":{},
				"Pyrrhonian Skepticism":{},
				"Varieties of Skepticism, Misc":{}
			},
			"Replies to Skepticism":{
				"Abductive Replies to Skepticism":{},
				"Contextualist Replies to Skepticism":{},
				"Dogmatist and Moorean Replies to Skepticism":{},
				"Externalist Replies to Skepticism":{},
				"Fallibilist Replies to Skepticism":{},
				"Relevance Replies to Skepticism":{},
				"Replies to Skepticism, Misc":{}
			},
			"Skepticism, Misc":{}},
		"Social Epistemology":{
			"Collective Epistemology":{},
			"Epistemology of Disagreement":{},
			"Social Epistemology, Misc":{},
			"Testimony":{}}},
	"Metaphilosophy":{
		"Epistemology of Philosophy":{
			"Metaphilosophical Skepticism":{},
			"Philosophical Methods":{}},
		"Metaphilosophical Views":{
			"Empiricism":{},
			"Naturalism":{},
			"Rationalism":{}},
		"Philosophical Methods":{
			"Arguments":{},
			"Conceptual Analysis":{},
			"Experimental Philosophy":{},
			"Formal Philosophy":{},
			"Linguistic Analysis":{},
			"Philosophical Methods, Misc":{},
			"Thought Experiments":{},
			"Transcendental Arguments":{}},
		"Metaphilosophy, Misc":{
			"Disagreement in Philosophy":{},
			"Kinds of Philosophy":{},
			"Metaontology":{},
			"Metaphilosophy, Misc":{},
			"The Nature of Philosophy":{},
			"The Nature of Analytic Philosophy":{},
			"Philosophical Language":{},
			"Philosophical Progress":{},
			"Philosophical Traditions":{},
			"The Role of Philosophy":{},
			"The Value of Philosophy":{}}},
	"Metaphysics":{
		"Causation, Laws, etc":{
			"Theories of Causation":{
				"Causal Eliminativism":{},
				"Causal Primitivism":{},
				"Causal Reductionism":{},
				"Counterfactual Theories":{},
				"Manipulability Theories":{},
				"Nomological Theories":{},
				"Occasionalism":{},
				"Process Theories":{},
				"Statistical Theories":{},
				"Theories of Causation, Misc":{}
			},
			"Varieties of Causation":{
				"Agent Causation":{},
				"Backward Causation":{},
				"Causal Overdetermination":{},
				"Causal Preemption":{},
				"Causation by Absences":{},
				"Downward Causation":{},
				"Mental Causation":{},
				"Probabilistic Causation":{},
				"Supervenient Causation":{},
				"Varieties of Causation, Misc":{}
			},
			"Causation, Misc":{
				"Causal Reasoning":{},
				"Causal Relata":{},
				"Causal Explanation":{},
				"Causation in the Law":{},
				"Singular Causation":{},
				"Causation, Misc":{}
			},
			"Chance and Objective Probability":{
				"Chance and Determinism":{},
				"Chance and Objective Probability, Misc":{},
				"Frequentism":{},
				"Logical Probability":{},
				"Probability Laws":{},
				"Propensities":{},
				"The Principal Principle":{}
			},
			"Dispositions and Powers":{
				"Bare Dispositions":{},
				"Dispositional and Categorical Properties":{},
				"Conditional Analyses":{},
				"Dispositions and Bases":{},
				"Finkish Dispositions":{},
				"Powers":{}
			},
			"Laws of Nature":{
				"Anti-Realism about Laws":{},
				"Best-Systems Analyses":{},
				"Ceteris Paribus Laws":{},
				"Humeanism and Nonhumeanism about Laws":{},
				"Lawlikeness":{},
				"Laws as Relations between Universals":{},
				"Necessitarianism about Laws":{},
				"Nomic Necessity":{},
				"Nomic Realism and Irrealism":{},
				"Probabilistic Laws":{}},
			"Miscellaneous":{}
		},
		"Global Metaphysical Theories":{
			"Dualism":{},
			"Idealism":{},
			"Logical Atomism":{},
			"Monism":{},
			"Naturalism":{},
			"Phenomenalism":{},
			"Physicalism":{
				"Causal Closure of the Physical":{},
				"Formulating Physicalism":{},
				"Nonreductive Materialism":{},
				"Supervenience and Physicalism":{},
				"Physicalism about the Mind":{},
				"Physicalism, Misc":{}
			},
			"Metaphysical Theories, Misc":{}
		},
		"Identity":{
			"Identity, Misc":{
				"Contingent Identity":{},
				"Identity of Indiscernibles":{},
				"Identity, Misc":{},
				"Relative Identity":{},
				"The Necessity of Identity":{}
			},
			"Identity Through Time":{
				"Endurance":{},
				"Perdurance":{},
				"Occasional Identity":{},
				"Relative Identity":{},
				"Stage Theory":{},
				"Three- and Four-Dimensionalism":{}
			},
			"Personal Identity":{
				"Personal Identity, General":{},
				"Survival and What Matters":{},
				"Persons":{},
				"The Self":{},
				"Psychological Theories":{},
				"Physical and Animalist Theories":{},
				"Fission and Split Brains":{},
				"Multiple Personality":{}
			}
		},
		"Interlevel Metaphysics":{
			"Conceptual Analysis and A Priori Entailment":{},
			"Emergence":{},
			"Fundamentality":{},
			"Realization":{},
			"Interlevel Relations, Misc":{},
			"Physicalism":{},
			"Reduction":{},
			"Supervenience":{
				"Moral Supervenience":{},
				"Psychophysical Supervenience":{},
				"Supervenience and Physicalism":{},
				"Supervenience, General":{},
				"Supervenient Causation":{}
			},
			"Token Identity":{},
			"Truthmakers":{}
		},
		"Metaontology":{
			"Metaontology, Misc":{},
			"Ontological Commitment":{},
			"Ontological Conventionalism":{},
			"Ontological Disagreement":{},
			"Ontological Pluralism":{},
			"Ontological Realism":{},
			"Ontological Relativism":{},
			"Quantification and Ontology":{}
		},
		"Modality":{
			"Essentialism and De Re Modality":{
			},
			"Varieties of Modality":{
			},
			"Theories of Modality":{
			},
			"Modal Epistemology":{
			},
			"Possible Worlds":{
			}
		},
		"Metaphysics, Misc":{}
	},
	"Philosophy of Action":{
		"Action Theory":{
			"The Nature of Action":{
				"Causal Theory of Action":{},
				"Defining Action":{},
				"The Nature of Action, Misc":{},
				"The Structure of Action":{}},
			"Varieties of Action":{
				"Collective Action":{},
				"Inaction":{},
				"Intentional Action":{},
				"Mental Actions":{},
				"Trying":{}},
			"Explanation of Action":{
				"Explanation of Action, Misc":{},
				"Mental Causation":{},
				"Psychological Explanation":{},
				"Reasons and Causes":{}},
			"Action, Misc":{
				"Action Sentences":{},
				"Consciousness of Action":{},
				"Intentional Action":{},
				"Knowledge of Action":{},
				"Perception and Action":{}},
			"Agency and Responsibility":{
				"Agency":{},
				"Agents":{},
				"Doing and Allowing":{},
				"Free Will and Responsibility":{},
				"Responsibility and Reactive Attitudes":{}},
			"Intentions and Plans":{
				"Collective Intentions":{},
				"Intentions":{},
				"Intentional Action":{},
				"Plans":{}},
			"Motivation and Will":{
				"Free Will":{},
				"Motivation":{},
				"The Will":{},
				"Weakness of Will":{}}},
		"Decision Theory":{
			"Decision-Theoretic Frameworks":{
				"Causal Decision Theory":{},
				"Evidential Decision Theory":{},
				"Other Decision-Theoretic Frameworks":{}},
			"Decision-Theoretic Puzzles":{
				"Newcomb's Problem":{},
				"Pascal's Wager":{},
				"St. Petersburg Paradox":{},
				"Two-Envelope Paradox":{}},
			"Game Theory":{
				"Convention and Coordination":{},
				"Evolutionary Game Theory":{},
				"Game-Theoretic Principles":{},
				"Game Theory and Ethics":{},
				"Game Theory and Political Philosophy":{},
				"Prisoner's Dilemma":{}},
			"Topics in Decision Theory":{
				"Decision Theory and Ethics":{},
				"Infinite Decision Theory":{},
				"Normative and Descriptive Decision Theory":{},
				"Utility":{}}},
		"Free Will":{
			"Free Will and Science":{
				"Free Will and Genetics":{},
				"Free Will and Neuroscience":{},
				"Free Will and Physics":{},
				"Free Will and Psychology":{},
				"Free Will and Science, Misc":{}},
			"The Will":{},
			"Theories of Free Will":{
				"Agent Causation":{},
				"Compatibilism":{},
				"Free Will Skepticism":{},
				"Identification Theories":{},
				"Incompatibilism":{},
				"Libertarianism":{},
				"Semi-Compatibilism":{}},
			"Topics in Free Will":{
				"Alternative Possibilities":{},
				"Determinism":{},
				"Free Will and Responsibility":{},
				"Free Will and Foreknowledge":{},
				"Responsibility and Reactive Attitudes":{},
				"Free Will, Misc":{}}},
		"Philosophy of Action, Misc":{},
		"Practical Reason":{
			"Moral Psychology":{},
			"Moral Reasoning and Motivation":{},
			"Practical Reason, Misc":{
				"Decision":{},
				"Deliberation":{},
				"Desire and Reason":{},
				"Instrumental Reasoning":{},
				"Normativity of Practical Reason":{},
				"Norms of Practical Reason":{},
				"Practical and Theoretical Reasoning":{},
				"Rational Requirements":{}},
			"Reasons":{
				"Internalism and Externalism about Reasons":{},
				"Reasons and Causes":{},
				"Reasons and Oughts":{},
				"Reasons and Rationality":{},
				"Subjective and Objective Reasons":{}}}},
	"Philosophy of Language":{
		"Languages":{
			"Idiolects":{},
			"Knowledge of Language":{},
			"Linguistic Universals":{},
			"Private Language":{},
			"Public Language":{},
			"Words":{}},
		"Meaning":{
			"The Basis of Meaning":{
				"Deflationary Theories":{},
				"Inferentialist Theories":{},
				"Interpretivist Theories":{},
				"Intention-Based Theories":{},
				"Naturalizing Content":{},
				"Thought-Based Theories":{},
				"Use Theories":{}},
			"Aspects of Meaning":{
				"Meaning Holism":{},
				"Meaning Skepticism":{},
				"Speaker Meaning and Semantic Meaning":{},
				"The Normativity of Meaning and Content"
				"Aspects of Meaning, Misc":{}},
			"Semantic Theories":{
				"Conceptual Semantics":{},
				"Event-Based Theories":{},
				"Fregean Theories":{
					"Frege's Puzzle":{},
					"Fregean Sense":{},
					"Fregean Theories of Attitude Ascriptions":{},
					"Fregean Theories, Misc":{}},
				"Intensional and Possible World Semantics":{},
				"Justificationist Semantics":{},
				"Relevance Theory":{},
				"Russellian and Direct Reference Theories":{
					"Direct Reference Theories of Indexicals":{},
					"Millian Theories of Names":{},
					"Russellian Theories of Attitude Ascriptions":{},
					"Singular Propositions":{},
					"Structured Propositions":{},
					"Russellian and Direct Reference Theories, Misc":{}},
				"Situation Theory":{},
				"Truth-Conditional Theories":{},
				"Two-Dimensional Semantics":{},
				"Type Theories":{},
				"The Nature of Contents":{},
				"Semantic Theories, Misc":{}},
			"Propositions":{
				"Attitude Ascriptions":{},
				"Pleonastic Propositions":{},
				"Propositional Attitudes":{},
				"Propositions and Facts":{},
				"Propositions and That-Clauses":{},
				"Propositions as Sets of Worlds":{},
				"Propositions, Misc":{},
				"Singular Propositions":{},
				"Structured Propositions":{},
				"The Unity of the Proposition":{},
				"The Nature of Contents":{}},
			"Semantic Phenomena":{
				"Ambiguity and Polysemy":{},
				"Analyticity":{},
				"Compositionality":{},
				"Context and Context-Dependence":{},
				"Conventional Implicature":{},
				"Definitions":{},
				"Intensionality and Opacity":{},
				"Interpretation":{},
				"Logical Form":{},
				"Nonliteral Meaning":{},
				"Meaning, Misc":{},
				"Scope":{},
				"Semantic Values":{},
				"Synonymy":{},
				"Translation":{}}},
		"Reference":{
			"Theories of Reference":{
				"Causal Theories":{},
				"Deflationary Theories":{},
				"Descriptive Theories":{},
				"Russellian and Direct Reference Theories":{},
				"Theories of Reference, Misc":{}},
			"Aspects of Reference":{
				"Empty Names":{},
				"Indeterminacy of Reference":{},
				"Intension and Extension":{},
				"Nonreferring Expressions":{},
				"Reference Failure":{},
				"Rigid Designation":{},
				"Reference, Misc":{},
				"Speaker Meaning and Semantic Meaning":{}}},
		"Philosophy of Linguistics":{
			"Syntax":{},
			"Semantics":{
				"Formal Semantics":{},
				"Generative Semantics":{},
				"Lexical Semantics":{},
				"Semantic Phenomena":{},
				"Semantic Theories":{},
				"Specific Expressions":{},
				"The Semantics-Pragmatics Distinction":{}},
			"Other Areas of Linguistics":{
				"Computational Linguistics":{},
				"Historical Linguistics":{},
				"Phonology":{},
				"Pragmatics":{},
				"Psycholinguistics":{},
				"Sociolinguistics":{}},
			"Methodology of Linguistics":{
				"Competence and Performance":{},
				"Linguistic Intuitions":{},
				"Prescriptivism and Descriptivism":{},
				"Psychological Reality":{}},
			"Philosophy of Linguistics, Misc":{
				"Linguistic Innateness":{},
				"Knowledge of Language":{},
				"The Status of Linguistic Theories":{}}},
		"Philosophy of Language, Misc":{
			"Feminist Philosophy of Language":{},
			"Language and Society":{},
			"Law and Language":{},
			"The Role of Language in Thought":{},
			"Use and Mention":{}},
		"Pragmatics":{
			"Assertion":{},
			"Communication":{},
			"Context and Context-Dependence":{
				"Character and Content":{},
				"Context and Logical Form":{},
				"Epistemic Contextualism":{},
				"Semantic Minimalism":{},
				"The Nature of Context":{},
				"The Scope of Context-Dependence":{},
				"Context and Context-Dependence, Misc":{}},
			"Discourse Representation":{},
			"Focus":{},
			"Force":{},
			"Implicature":{
				"Conventional Implicature":{},
				"Conversational Implicature":{},
				"Implicature, Misc":{}},
			"Metaphor":{},
			"Performatives":{},
			"Presupposition":{},
			"Semantics-Pragmatics Distinction":{},
			"Speech Acts":{}},
		"Specific Expressions":{
			"Adverbs":{},
			"Attitude Ascriptions":{
				"Attitude Ascriptions, Misc":{},
				"Desire Ascriptions":{},
				"Fregean Theories of Attitude Ascriptions":{},
				"Russellian Theories of Attitude Ascriptions":{},
				"Frege's Puzzle":{},
				"Hidden-Indexical Theories of Attitude Ascriptions":{},
				"Substitutivity in Attitude Ascriptions":{}},
			"Conditionals":{
				"Truth-Conditional Accounts of Indicative Conditionals":{},
				"Epistemic Accounts of Indicative Conditionals":{},
				"Pragmatic Accounts of Indicative Conditionals":{},
				"Indicative Conditionals and Conditional Probabilities":{},
				"Indicative Conditionals, Misc":{},
				"Counterfactuals and Possible Worlds":{},
				"Subjunctive Conditionals, Misc":{},
				"Conditionals, Misc":{}},
			"Connectives":{
				"Causal Connectives":{},
				"Explanatory Connectives":{},
				"Conditionals":{},
				"Conjunction":{},
				"Connectives, Misc":{},
				"Disjunction":{},
				"Negation":{}},
			"Descriptions":{
				"Attributive and Referential Uses of Descriptions":{},
				"Descriptions as Predicates":{},
				"Descriptive Theories of Reference":{},
				"Descriptive Theories of Names":{},
				"Incompleteness of Descriptions":{},
				"Indefinite Descriptions":{},
				"Presuppositional Account of Descriptions":{},
				"Russell's Theory of Descriptions":{}},
			"Determiners":{
				"Articles":{},
				"Complex Demonstratives":{},
				"Determiners, Misc":{},
				"Numerical Expressions":{},
				"Possessives":{},
				"Quantifiers":{}},
			"Generics":{},
			"Indexicals and Demonstratives":{
				"Character and Content":{},
				"Complex Demonstratives":{},
				"Demonstratives, Misc":{},
				"Direct Reference Theories of Indexicals":{},
				"Indexicals, Misc":{},
				"The First-Person Pronoun":{},
				"Pure and Impure Indexicals":{}},
			"Modal Expressions":{
				"Counterfactuals and Possible Worlds":{},
				"Epistemic Modals":{},
				"Modal Expressions, Misc":{}},
			"Names":{
				"Causal Theories of Names":{},
				"Demonstrative Theories of Names":{},
				"Descriptive Theories of Names":{},
				"Empty Names":{},
				"Frege's Puzzle":{},
				"Millian Theories of Names":{},
				"Rigid Designation":{}},
			"Nouns":{
				"Singular Terms":{},
				"General Terms":{},
				"Kind Terms":{},
				"Names":{},
				"Mass Nouns and Count Nouns":{}},
			"Predicates":{
				"Adjectives, Misc":{},
				"Gradable Adjectives":{},
				"Predicates and Context-Depdnence":{},
				"Kinds of Predicate":{},
				"States, Activities, Accomplishments, Achievements":{},
				"Taste Predicates":{},
				"Predicates, Misc":{}},
			"Pronouns and Anaphora":{},
			"Quantifiers":{
				"Generalized Quantifiers":{},
				"Plural Quantification":{},
				"Quantification and Ontology":{},
				"Quantifier Restriction":{},
				"Unrestricted Quantification":{},
				"Substitutional Quantification":{},
				"Variables":{}},
			"Questions":{},
			"Quotation":{},
			"Temporal Expressions":{},
			"Verbs":{
				"Attitude Ascriptions":{},
				"Intensional Transitive Verbs":{},
				"States, Activities, Accomplishments, Achievements":{}},
			"Other Expressions":{}},
		"Syntax":{
			"Syntactic Phenomena":{
				"Binding":{},
				"Ellipsis":{},
				"Grammaticality":{},
				"Scope":{},
				"Syntactic Categories":{},
				"Syntactic Phenomena, Misc":{}},
			"Syntactic Theories":{
				"Government and Binding":{},
				"The Minimalist Program":{},
				"Nontransformational Grammars":{},
				"Transformational Grammar":{},
				"Universal Grammar":{}},
			"Linguistic Innateness":{
				"Linguistic Innateness, Misc":{},
				"Linguistic Universals":{},
				"Poverty of the Stimulus":{},
				"Universal Grammar":{}}},
		"Truth and Vagueness":{
			"Theories of Truth":{
				"Coherence Theory of Truth":{},
				"Correspondence Theory of Truth":{},
				"Minimalism and Deflationism about Truth":{},
				"Pragmatism about Truth":{},
				"Tarskian Theories of Truth":{},
				"Theories of Truth, Misc":{}},
			"Truth, Misc":{
				"Relativism about Truth":{},
				"Truth Bearers":{},
				"Truth and Justification":{},
				"Truthmakers":{}},
			"The Liar Paradox":{},
			"Theories of Vagueness":{
				"Contextual Theories of Vagueness":{},
				"Degree-Theoretic Theories of Vagueness":{},
				"Epistemic Theories of Vagueness":{},
				"Incoherentism about Vagueness":{},
				"Nihilism about Vagueness":{},
				"Many-Valued Logic":{},
				"Supervaluationism":{},
				"Theories of Vagueness, Misc":{}},
			"Vagueness, Misc":{
				"Higher-Order Vagueness":{},
				"Vague Objects":{},
				"Vagueness in Ethics and the Law":{}
			}
		}
	},
	"Philosophy of Mind":{
		"Philosophy of Consciousness":{
			"Consciousness":{
				"Consciousness, General Works":{},
				"The Concept of Consciousness":{},
				"Consciousness, Miscellaneous":{}},
			"Explaining Consciousness?":{
				"What is it Like?":{},
				"Subjectivity and Objectivity":{},
				"The Explanatory Gap":{},
				"`Hard' and `Easy' Problems":{},
				"Cognitive Closure":{},
				"Conceptual Analysis and A Priori Entailment":{},
				"Explaining Consciousness, Misc":{}},
			"Consciousness and Materialism":{
				"The Knowledge Argument":{},
				"Zombies and the Conceivability Argument":{},
				"Kripke's Modal Argument":{},
				"Arguments from Disembodiment":{},
				"Other Anti-Materialist Arguments":{},
				"Qualia and Materialism":{},
				"Consciousness and Materalism, Misc":{},
				"Mind-Body Problem, General":{}},
			"Specific Views on Consciousness":{
				"Higher-Order Thought Approaches":{},
				"Representationalism":{},
				"Self-Representational Approaches":{},
				"Dennett's Functionalism":{},
				"Searle's Biological Naturalism":{},
				"Functionalism about Consciousness":{},
				"Eliminativism about Consciousness":{},
				"Dualism about Consciousness":{},
				"Panpsychism":{},
				"Russellian Monism":{},
				"Neutral Monism":{},
				"Idealism":{},
				"Phenomenalism":{},
				"Metaphysics of Consciousness, Misc":{}},
			"Consciousness and Content":{
				"Consciousness and Intentionality":{},
				"Representationalism":{},
				"Phenomenal Intentionality":{},
				"Conscious Thought":{},
				"Internalism and Externalism about Experience":{},
				"Phenomenal Concepts":{},
				"Consciousness and Content, Misc":{}},
			"Aspects of Consciousness":{
				"Self-Consciousness":{},
				"The Unity of Consciousness":{},
				"Homogeneity of Consciousness":{},
				"Knowledge of Consciousness":{},
				"The Function of Consciousness":{},
				"Temporal Consciousness":{},
				"Consciousness of Agency":{},
				"Bodily Experience":{},
				"Perceptual Experience":{},
				"Attention and Consciousness":{},
				"Emotions and Consciousness":{},
				"Unconscious States":{},
				"Collective Consciousness":{}},
			"Qualia":{
				"Qualia, General":{},
				"Qualia and Materialism":{},
				"Eliminativism about Qualia":{},
				"The Inverted Spectrum":{},
				"Absent Qualia":{},
				"Functionalism and Qualia":{}},
			"Science of Consciousness":{}},
		"Intentionality":{
			"Propositional Attitudes":{
				"The Language of Thought":{},
				"The Intentional Stance":{},
				"Eliminativism":{},
				"Belief":{},
				"Desire":{},
				"Thought and Thinking":{},
				"Propositions":{},
				"Attitude Ascriptions":{},
				"Propositional Attitudes, General":{}},
			"Content Internalism and Externalism":{
				"Is Content in the Head?":{},
				"Social Externalism":{},
				"Externalism and Psychological Explanation":{},
				"Externalism and Mental Causation":{},
				"Externalism and the Theory of Vision":{},
				"Externalism and Computation":{},
				"Externalism and Self-Knowledge":{},
				"Narrow Content":{},
				"Two-Dimensionalism about Content":{},
				"The Extended Mind":{},
				"Internalism and Externalism about Experience":{},
				"Internalism and Externalism, Misc":{}},
			"Naturalizing Content":{
				"Information-Based Accounts":{},
				"Asymmetric Dependence":{},
				"Causal Accounts, General":{},
				"Teleological Approaches":{},
				"Conceptual Role Approaches":{},
				"Interpretivist Approaches":{},
				"Phenomenal Intentionality":{},
				"Naturalizing Content, Misc":{}},
			"The Nature of Contents":{
				"Conceptual and Nonconceptual Content":{},
				"The Contents of Perception":{},
				"Fregean and Russellian Contents":{},
				"Indexical Contents":{},
				"Intentional Objects":{},
				"Narrow Content":{},
				"Object-Dependent Contents":{},
				"Propositions":{},
				"Two-Dimensionalism about Content":{}},
			"Aspects of Intentionality":{
				"Naturalism and Intentionality":{},
				"Meaning Skepticism":{},
				"Rule-Following":{},
				"The Normativity of Meaning and Content":{},
				"Meaning Holism":{},
				"The Explanatory Role of Content":{},
				"Collective Intentionality":{},
				"Intentionality, Misc":{}},
			"Representation":{
				"The Concept of Representation":{},
				"Varieties of Representation":{},
				"Theories of Representation":{},
				"Skepticism About Representations":{},
				"Representation in Cognitive Science":{},
				"Representation in Neuroscience":{},
				"Pictorial Representation":{},
				"Computation and Representation":{}},
			"Concepts":{
				"Perception-Based Theories of Concepts":{},
				"Inferential Theories of Concepts":{},
				"Prototype and Exemplar Theories of Concepts":{},
				"Theory-Based Theories of Concepts":{},
				"Atomist Theories of Concepts":{},
				"Theories of Concepts, Misc":{},
				"Conceptual Analysis":{},
				"Conceptual Change":{},
				"Concept Possession":{},
				"Ontology of Concepts":{},
				"Phenomenal Concepts":{},
				"Recognitional Concepts":{},
				"Theories of Concepts":{}},
			"Mental Content, Misc":{}},
		"Perception":{
			"The Nature of Perceptual Experience":{
				"Sense-Datum Theories":{},
				"Adverbialism and Qualia Theories":{},
				"Intentionalism":{},
				"Belief Theories":{},
				"Naive and Direct Realism":{},
				"Disjunctivism":{},
				"The Nature of Perceptual Experience, Misc":{}},
			"The Perceptual Relation":{
				"The Causal Theory of Perception":{},
				"Direct and Indirect Perception":{},
				"The Objects of Perception":{},
				"The Perceptual Relation, Misc":{}},
			"The Contents of Perception":{
				"Conceptual and Nonconceptual Content":{},
				"Color Experience":{},
				"Spatial Experience":{},
				"The Experience of Objects":{},
				"The Experience of High-Level Properties":{},
				"The Contents of Perception, Misc":{}},
			"Sensory Modalities":{
				"Distinguishing the Senses":{},
				"Vision":{},
				"Other Sensory Modalities":{},
				"Molyneux's Problem":{},
				"The Senses, Misc":{}},
			"The Science of Perception":{
				"Modularity and Cognitive Penetrability":{},
				"Ecological Approaches to Perception":{},
				"Construction and Inference in Perception":{},
				"Perception and Neuroscience":{},
				"Psychophysics":{},
				"Gestalt Theory":{},
				"Visual Consciousness":{}},
			"Perception and the Mind":{
				"Perceptual Knowledge":{},
				"Perception and Thought":{},
				"Perception and Action":{},
				"Perception and Reference":{},
				"Perception and Phenomenology":{},
				"Perception-Based Theories of Concepts":{}},
			"Perceptual Knowledge":{
				"Discriminability":{},
				"Dogmatism about Perception":{},
				"Epistemic and Non-epistemic Perception":{},
				"Naive and Direct Realism":{},
				"Perceptual Justification":{},
				"Perception and Knowledge, Misc":{},
				"Perception and Skepticism":{},
				"Sense-Datum Theories":{},
				"The Given":{}},
			"Perceptual Qualities":{
				"Color":{},
				"Sound":{},
				"Discriminability":{},
				"Primary and Secondary Qualities":{},
				"Perceptual Qualities, Misc":{},
				"Qualia":{}},
			"Special Topics":{
				"Illusion and Hallucination":{},
				"Transparency":{},
				"The Given":{},
				"Perceptual Reports":{},
				"Sensation and Perception":{}},
			"Philosophy of Perception, General":{}},
		"Metaphysics of Mind":{
			"Physicalism about the Mind":{
				"Consciousness and Materialism":{},
				"Qualia and Materialism":{},
				"Identity Theory":{},
				"Eliminative Materialism":{},
				"Anomalous Monism":{},
				"Nonreductive Materialism":{},
				"Physicalism about the Mind, Misc":{},
				"Physicalism":{}},
			"Dualism":{
				"Causal Closure of the Physical":{},
				"Interactionism":{},
				"Epiphenomenalism":{},
				"Psychophysical Parallelism":{},
				"Dualism about Consciousness":{},
				"Dualism, Misc":{}},
			"Behaviorism":{
				"Logical Behaviorism":{},
				"Psychological Behaviorism":{},
				"Behaviorism, Misc":{}},
			"Functionalism":{
				"Causal Role Functionalism":{},
				"Machine Functionalism":{},
				"Functionalism About Consciousness":{},
				"Functionalism and Qualia":{},
				"Functionalism, Misc":{}},
			"Other Psychophysical Theories":{
				"Idealism":{},
				"Neutral Monism":{},
				"Panpsychism":{},
				"Russellian Monism":{}},
			"Psychophysical Reduction":{
				"Nonreductive Materialism":{},
				"Reduction in Psychology and Neuroscience":{},
				"Reduction and Multiple Realizability":{},
				"Psychophysical Reduction, Misc":{}},
			"Other Psychophysical Relations":{
				"Conceptual Analysis and A Priori Entailment":{},
				"Emergence":{},
				"Realization":{},
				"Psychophysical Supervenience":{},
				"Token Identity":{},
				"Interlevel Relations, Misc":{}},
			"Mental Causation":{
				"Anomalous Monism and Mental Causation":{},
				"Causal Overdetermination":{},
				"Causal Closure of the Physical":{},
				"Downward Causation":{},
				"Epiphenomenalism":{},
				"Explanatory Role of Content":{},
				"Externalism and Mental Causation":{},
				"Functionalism and Mental Causation":{},
				"Psychological Explanation":{},
				"Reasons and Causes":{},
				"Supervenient Causation":{},
				"The Exclusion Problem":{},
				"The Function of Consciousness":{},
				"Mental Causation, Misc":{}},
			"Personal Identity":{},
			"Free Will":{},
			"Metaphysics of Mind, Misc":{}},
		"Epistemology of Mind":{
			"Self-Knowledge":{
				"Observational Accounts":{},
				"Commitment/Expression-Based Accounts":{},
				"Constitutive Accounts":{},
				"Externalism and Self-Knowledge":{},
				"Knowledge of Consciousness":{},
				"First-Person Authority and Privileged Access":{},
				"First-Person Approaches to the Science of Consciousness":{},
				"Introspection and Introspectionism":{},
				"Infallibility and Incorrigibility":{},
				"Self-Deception":{},
				"Self-Knowledge, Misc":{}},
			"The Problem of Other Minds":{
				"Analogy and Other Minds":{},
				"Abduction and Other Minds":{},
				"Criteria and Other Minds":{},
				"Direct Knowledge and Other Minds":{},
				"Induction and Other Minds":{},
				"Other Minds, Misc":{},
				"Private Language and Other Minds":{}},
			"Perceptual Knowledge":{},
			"Epistemology of Mind, Misc":{}},
		"Mental States":{
			"Attention":{
				"Attention and Consciousness":{},
				"Attention, Misc":{},
				"Change/Inattentional Blindness":{},
				"Science of Consciousness and Attention":{},
				"The Nature of Attention":{}},
			"Belief":{
				"Attitude Ascriptions":{},
				"Belief, Misc":{},
				"Belief Revision":{},
				"Collective Belief":{},
				"Degrees of Belief":{},
				"De Re Belief":{},
				"Doxastic Voluntarism":{},
				"The Ethics of Belief":{},
				"The Nature of Belief":{},
				"Tacit and Dispositional Belief":{}},
			"Bodily Experience":{
				"Bodily Awareness":{},
				"Bodily Experience, Misc":{},
				"Bodily Sensations":{},
				"Embodiment and Situated Cognition":{},
				"Pain":{}},
			"Desire":{
				"Desire and Reason":{},
				"Desire as Belief":{},
				"Desire-Satisfaction Theories of Well-Being":{},
				"Pleasure and Desire":{},
				"Theories of Desire, Misc":{},
				"Desire, Misc":{}},
			"Dreams":{
				"Consciousness, Sleep, and Dreaming":{},
				"Dreams and Skepticism":{},
				"Dreams, Misc":{},
				"The Nature of Dreaming":{}},
			"Emotions":{
				"Aesthetic Emotion":{},
				"Classifying Emotions":{},
				"Cognitive Theories of Emotions":{},
				"Emotivism and Sentimentalism":{},
				"Emotions and Appraisals":{},
				"Emotions and Consciousness":{},
				"Emotions and Feelings":{},
				"Emotion and Rationality":{},
				"Moods":{},
				"Music and Emotion":{},
				"Objects and Contents of Emotions":{},
				"Science of Consciousness and Emotion":{},
				"The Nature of Emotion, Misc":{}},
			"Imagery":{},
			"Imagination":{
				"Conceivability, Imagination, and Possibility":{},
				"Imaginative Resistance":{},
				"Imagination and Imagery":{},
				"Imagination and Pretense":{},
				"Imagination, Misc":{},
				"Visual Imagery and Imagination":{}},
			"Intuition":{},
			"Memory":{
				"Epistemology of Memory":{},
				"Memory and Cognitive Science":{},
				"Memory, Misc":{},
				"The Nature of Memory":{}},
			"Mental Actions":{},
			"Moral Psychology":{},
			"Pain":{
				"The Concept of Pain":{},
				"Location of Pain":{},
				"Pain and Pain Experience":{},
				"Pain and Perception":{},
				"Pain, Misc":{},
				"Pain and Mental Objects":{},
				"Pleasure and Pain":{}},
			"Pleasure":{
				"Aesthetic Pleasure":{},
				"Hedonism":{},
				"Pleasure and Desire":{},
				"Pleasure and Pain":{},
				"Pleasure, Misc":{},
				"The Value of Pleasure":{}},
			"Thought and Thinking":{
				"Conscious Thought":{},
				"Reasoning":{}},
			"Mental States, Misc":{}},
		"Philosophy of Cognitive Science":{},
		"Philosophy of Mind, Miscellaneous":{
			"Collective Mentality":{
				"Collective Action":{},
				"Collective Belief":{},
				"Collective Consciousness":{},
				"Collective Epistemology":{},
				"Collective Intentionality":{},
				"Collective Intentions":{}},
			"Philosophy of Mind, General":{},
			"Philosophy of Mind, Misc":{}
		}
	},
	"Philosophy of Religion":{
		"Arguments for Theism":{
			"Cosmological Arguments":{},
			"Design Arguments":{},
			"Moral Arguments":{},
			"Ontological Arguments":{},
			"Pragmatic Arguments":{},
			"Arguments for Theism, Misc":{}},
		"Gods and their Properties":{
			"Benevolence":{},
			"Divine Freedom":{},
			"Divine Foreknowledge":{},
			"Divine Simplicity":{},
			"Gods, Misc":{},
			"Omnipotence":{},
			"Omniscience":{}},
		"Epistemology of Religion":{
			"Epistemology of Religion, Misc":{},
			"Faith":{},
			"Reformed Epistemology":{},
			"Religious Experience":{},
			"Revelation":{}},
		"Religious Views":{
			"Atheism and Agnosticism":{},
			"Monotheism, Polytheism, Pantheism":{},
			"Specific Religions":{
				"Buddhism":{},
				"Christianity":{
					"Heaven and Hell":{},
					"The Incarnation":{},
					"The Trinity":{}},
				"Hinduism":{},
				"Islam":{},
				"Judaism":{},
				"Other Religions":{}}},
		"Religious Topics":{
			"Afterlife":{
				"Afterlife, Misc":{},
				"Heaven and Hell":{},
				"Reincarnation":{},
				"Resurrection":{}},
			"Creation":{
				"Creation, Misc":{},
				"Evolution and Creationism":{}},
			"Evil":{
				"Moral Evil":{},
				"Natural Evil":{},
				"The Argument from Evil":{},
				"Evil, Misc":{}},
			"Miracles":{},
			"Prayer":{},
			"Sin":{}
		}},
	"M&E, Misc":{}
},
"Value Theory":{
	"Aesthetics":{
		"Aesthetic Cognition":{
			"Aesthetic Attitudes":{},
			"Aesthetic Concepts":{},
			"Aesthetic Emotion":{},
			"Aesthetic Experience":{},
			"Aesthetic Judgment":{},
			"Aesthetic Perception":{},
			"Aesthetic Pleasure":{},
			"Aesthetic Taste":{},
			"Aesthetic Understanding":{},
			"Aesthetics and Cognitive Science":{}},
		"Aesthetic Qualities":{
			"Aesthetic Qualities, Misc":{},
			"Beauty":{},
			"Style":{}},
		"Aesthetic Realism":{
			"Aesthetic Realism":{},
			"Relativism":{},
			"Subjectivism":{},
			"Universality":{}},
		"Aesthetic Representation and Meaning":{
			"Aesthetic Symbol Systems":{},
			"Depiction":{},
			"Intention and Intepretation":{}},
		"Aesthetic Value":{
			"Aesthetic Criticism":{},
			"Aesthetic Evaluation":{},
			"Aesthetic Normativity":{},
			"Aesthetics and Ethics":{},
			"The Value of Art":{}},
		"Aesthetics and Culture":{
			"Aesthetic Universals":{},
			"Crosscultural Aesthetics":{},
			"Pop Culture":{}},
		"Aesthetics, Misc":{
			"Aesthetics of Nature":{}},
		"Art and Artworks":{
			"Artworks":{},
			"The Artworld":{},
			"The Definition of Art":{},
			"The Value of Art":{}},
		"Philosophy of Arts, Misc":{
			"Architecture":{},
			"Comics":{},
			"Dance":{},
			"Design":{},
			"Fashion":{},
			"Food and Drink":{},
			"Humour":{},
			"Opera":{},
			"Theatre":{}},
		"Philosophy of Film":{
			"Cinema":{},
			"Television":{},
			"Video":{},
			"Philosophy of Film, Misc":{}},
		"Philosophy of Music":{
			"Definition of Music":{},
			"Ontology of Music":{
				"Musical Ontology, Misc":{},
				"Musical Performance":{},
				"Musical Works":{}},
			"Musical Experience":{
				"Music and Emotion":{},
				"Musical Experience, Misc":{},
				"Musical Expression":{},
				"Musical Understanding":{}},
			"Varieties of Music":{
				"Classical Music":{},
				"Folk Music":{},
				"Jazz":{},
				"Opera":{},
				"Popular Music":{},
				"Varieties of Music, Misc":{}}},
		"Philosophy of Literature":{
			"Fiction":{
				"Fictional Characters":{},
				"Fictionalism":{},
				"Narrative":{},
				"Truth in Fiction":{}},
			"Nonfiction":{},
			"Poetry":{},
			"Literature, Misc":{}},
		"Philosophy of Visual Art":{
			"Painting and Drawing":{},
			"Photography":{},
			"Pictorial Representation":{},
			"Sculpture":{}}},
	"Applied Ethics":{
		"Academic Ethics":{},
		"Applied Ethics, Misc":{
			"General Issues in Applied Ethics":{
				"Autonomy":{},
				"Benevolence":{},
				"Benificence":{},
				"Harm":{},
				"Honesty":{},
				"Justice":{},
				"Lawfulness":{},
				"Paternalism":{},
				"Rights":{}}},
	 	"Biomedical Ethics":{
				"Death and Dying":{},
				"Assisted Suicide":{},
				"Brain Death":{},
				"Capital Punishment":{},
				"Cryonics":{},
				"Defining Death":{},
				"Euthanasia":{},
				"Genocide":{},
				"Infanticide":{},
				"Life Support":{},
				"Suicide":{},
				"The Badness of Death":{}},
			"Drugs":{
				"Drug Addiction":{},
				"Pharmaceuticals":{},
				"Recreational Drugs":{}},
			"Genetic Ethics":{
				"Cloning":{},
				"Eugenics":{},
				"Genetic Engineering":{},
				"Genetic Modification":{},
				"Genetic Testing":{}},
			"Health Care Ethics":{
				"Disability":{},
				"Disease":{},
				"Health":{},
				"Health Care Justice":{},
				"Health Care Rights":{},
				"Illness":{},
				"Informed Consent":{},
				"Nursing":{},
				"Welfare":{}},
			"Medical Ethics":{
				"Advance Directives":{},
				"Benificence":{},
				"Confidentiality":{},
				"Informed Consent":{},
				"Life Extension":{},
				"Malpractice":{},
				"Medical Research Ethics":{},
				"Organ Donation":{},
				"Organ Transplantation":{},
				"Psychiatry":{},
				"Therapeutic Cloning":{}},
			"Neuroethics":{
				"Brain Death":{},
				"Brain Imaging":{},
				"Cognitive Enhancement":{},
				"Neuroethics, Misc":{},
				"Neuroscience of Ethics":{},
				"Psychopathology":{},
				"Vegetative and Post-Coma States":{}},
			"Reproductive Ethics":{
				"Abortion":{},
				"Cloning":{},
				"Contraception":{},
				"Parenthood":{},
				"Morality of Procreation":{},
				"Sex Selection":{},
				"Sperm and Egg Donation":{},
				"Stem Cell Research":{},
				"Surrogate Motherhood":{}},
		"Environmental Ethics":{
			"Animal Ethics":{
				"Animal Cruelty":{},
				"Animal Rights":{},
				"Speciesism":{},
				"Vegetarianism":{}},
			"Environmental Value":{
				"Cost-Benefit Analysis":{},
				"Diversity":{},
				"Intrinsic Value":{},
				"Instrumental Value":{}},
			"Environmental Philosophies":{
				"Conservation Ethics":{},
				"Deep Ecology":{},
				"Ecofeminism":{},
				"Environmental Pluralism":{},
				"Environmental Pragmatism":{},
				"Humanist Theories":{},
				"Social Ecology":{}},
			"Topics in Environmental Philosophy":{
				"Climate Change":{},
				"Ecology and Conservation Biology":{},
				"Environmental Justice":{},
				"Future Generations":{},
				"Nature":{},
				"Pollution":{},
				"Species":{},
				"Sustainability":{},
				"Wilderness":{}}},
		"Gender, Race, and Sexuality":{},
		"Professional Ethics":{
			"Academic Ethics":{},
			"Business Ethics":{},
			"Media Ethics":{},
			"Military Ethics":{},
			"Legal Ethics":{},
			"Professional Ethics, Misc":{}},
		"Political Ethics":{
			"Criminal Justice Ethics":{
				"Policing":{},
				"Punishment":{},
				"Capital Punishment":{}},
			"Government Ethics":{},
			"International Ethics":{
				"Famine":{},
				"Global Justice":{},
				"War and Violence":{}}},
		"Social Ethics":{
			"Family Ethics":{
				"Childhood":{},
				"Parenthood":{}},
			"Friendship":{},
			"Sexual Ethics":{
				"Prostitution":{},
				"Pornography":{},
				"Sexual Orientation":{},
				"Sexual Ethics, Misc":{}}},
		"Technology Ethics":{
			"Computer Ethics":{
				"Internet Ethics":{}},
			"Nanotechnology":{}}},
	"Meta-Ethics":{
		"Meta-Ethics, Misc":{},
		"Moral Judgment":{
			"Amoralists":{},
			"Moral Cognitivism":{},
			"Moral Emotivism and Sentimentalism":{},
			"Moral Expressivism":{},
			"Internalism and Externalism about Moral Judgment":{},
			"Moral Noncognitivism":{}},
		"Moral Naturalism and Non-Naturalism":{
			"Moral Nonnaturalism":{},
			"Moral Supervenience":{},
			"The Naturalistic Fallacy":{},
			"The Open Question Argument":{},
			"The Is/Ought Gap":{}},
		"Moral Realism and Irrealism":{
			"Moral Realism":{
				"Moral Cognitivism":{},
				"Moral Constructivism":{},
				"Cornell Realism":{},
				"Moral Descriptivism":{},
				"Moral Functionalism":{},
				"Moral Rationalism":{},
				"Moral Realism, Misc":{},
				"Moral Nonnaturalism":{},
				"Moral Sensibility Theories":{}},
			"Moral Irrealism":{
				"Moral Emotivism and Sentimentalism":{},
				"Moral Error Theories and Fictionalism":{},
				"Moral Expressivism":{},
				"Moral Irrealism, Misc":{},
				"Moral Noncognitivism":{},
				"Moral Prescriptivism":{},
				"Moral Projectivism":{},
				"Moral Relativism":{},
				"Moral Subjectivism":{}},
			"Moral Realism and Irrealism, Misc":{
				"Ideal Observer Theories":{},
				"Moral Constructivism":{},
				"Moral Explanation":{},
				"Moral Objectivity":{},
				"Moral Queerness":{},
				"Quasi-Realism":{},
				"Moral Response-Dependence":{}}},
		"Moral Epistemology":{
			"Moral Coherentism":{},
			"Moral Intuitionism":{},
			"Moral Disagreement":{},
			"Moral Justification":{},
			"Moral Rationalism":{},
			"Moral Skepticism":{},
			"Reflective Equilibrium":{}},
		"Moral Language":{
			"Moral Expressivism":{},
			"Moral Prescriptivism":{},
			"Moral Semantics":{}},
		"Moral Normativity":{
			"Ought Implies Can":{},
			"Moral Normativity, Misc":{},
			"Moral Norms":{},
			"Values and Norms":{}},
		"Moral Principles":{
			"Hypothetical and Categorical Imperatives":{},
			"Moral Generalism":{},
			"Moral Generalizations":{},
			"Moral Particularism":{},
			"Moral Principles, Misc":{},
			"Moral Universalizability":{}},
		"Moral Reasoning and Motivation":{
			"Internalism and Externalism about Moral Judgment":{},
			"Internalism and Externalism about Reasons":{},
			"Moral Judgment":{},
			"Moral Concepts":{},
			"Moral Motivation":{},
			"Moral Rationality":{},
			"Moral Reasons":{}},
		"Moral Responsibility":{},
		"Moral Value":{}},
	"Normative Ethics":{
		"Ethical Theories":{
			"Anti-Theory":{},
			"Consequentialism":{
				"Agent-Centered and Agent-Relative Value":{},
				"Consequentialism, Misc":{},
				"Indirect Justification":{},
				"Moral Value":{},
				"Rule Consequentialism":{},
				"Utilitarianism":{
					"Act- and Rule-Utilitarianism":{},
					"Utility":{}},
				"Self-Effacingness":{},
				"Satisficing":{},
				"Teleology":{}},
			"Moral Contractualism and Contractarianism":{},
			"Deontological Moral Theories":{
				"Kantian Ethics":{
					"The Categorical Imperative":{
						"Formula of Universal Law":{},
						"Formula of Humanity":{},
						"Formula of the Kingdom of Ends":{},
						"Categorical and Hypothetical Imperatives":{},
						"The Categorical Imperative, Misc":{}},
					"The Good Will and Moral Worth":{},
					"Contradictions in Conception and in the Will":{},
					"Perfect and Imperfect Duties":{}},
				"Natural Law Theory":{},
				"Moral Pluralism":{},
				"The Doctrine of Double Effect":{},
				"Doing and Allowing":{},
				"Ought Implies Can":{}},
			"Ethical Egoism":{},
			"Virtue Ethics":{},
			"Ethical Theories, Misc":{}},
		"Moral Value":{
			"Agent-Centered and Agent-Relative Value":{},
			"Axiology":{},
			"Buck-Passing":{},
			"Fact-Value Distinction":{},
			"Incommensurability":{},
			"Intrinsic Value":{},
			"Moral Worth":{},
			"Neutral and Relative Value":{},
			"The Good":{},
			"The Meaning of Life":{},
			"Values and Norms":{},
			"Well-Being":{
				"Hedonism":{},
				"Desire Satisfaction Accounts":{},
				"Objective List Accounts":{},
				"Perfectionism":{},
				"Well-Being, Misc":{}}},
		"Moral Phenomena":{
			"Desert":{},
			"Moral Dilemmas":{},
			"Moral Luck":{},
			"Moral Sainthood":{},
			"Obligation":{},
			"Promises":{},
			"Suberogation":{},
			"Supererogation":{}},
		"Moral Psychology":{
			"Altruism and Psychological Egoism":{},
			"Ethics and Cognitive Science":{
				"Evolution of Morality":{},
				"Neuroscience of Ethics":{},
				"Neuroethics":{},
				"Psychology of Ethics":{},
				"Skepticism about Character":{}},
			"Moral Character":{
				"Amoralists":{},
				"Integrity":{},
				"Moral Sainthood":{},
				"Skepticism about Character":{},
				"Virtues and Vices":{}},
			"Moral Judgment":{},
			"Moral Reasoning and Motivation":{},
			"Moral States and Processes":{
				"Alienation":{},
				"Anger":{},
				"Courage":{},
				"Cruelty":{},
				"Emotion":{},
				"Envy":{},
				"Gratitude":{},
				"Guilt and Shame":{},
				"Happiness":{},
				"Hypocrisy":{},
				"Jealousy":{},
				"Kindness":{},
				"Love":{},
				"Moral Deliberation":{},
				"Moral Perception":{},
				"Moral Phenomenology":{},
				"Resentment":{},
				"Schadenfreude":{},
				"Self-Deception":{},
				"Sympathy":{},
				"Trust":{}
			}
		}
	},
	"Philosophy of Education":{
		"The Nature of Education":{},
		"The Aims of Education":{},
		"Educational Authority":{},
		"Philosophy of Education, Misc":{},
		"Philosophy of Teaching":{},
		"Philosophy of Childhood":{}},
	"Philosophy of Gender, Race, and Sexuality":{
		"Feminist Philosophy":{},
		"Philosophy of Gender, Misc":{},
		"Philosophy of Race":{},
		"Philosophy of Sexual Orientation":{},
		"Philosophy of Sexuality, Misc":{}},
	"Philosophy of Law":{
		"The Nature of Law and Legal Systems":{
			"Interpretivist Theories":{},
			"Legal Positivism":{},
			"Natural Law Theory":{},
			"Legal Realism":{},
			"Mixed Theories":{},
			"Nature of Law, Misc":{}},
		"Legal Reasoning and Adjudication":{
			"Formalism":{},
			"Realism":{},
			"Indeterminacy of Legal Reasoning":{},
			"Formal Models of Legal Reasoning":{}},
		"Legal Authority and Obligation":{
			"Legal Authority":{},
			"Political Obligation":{},
			"Obligations in the Law":{}},
		"Methodology of Jurisprudence":{
			"Descriptive Jurisprudence":{},
			"Normative Jurisprudence":{},
			"Conceptual Analysis":{},
			"Naturalism":{}},
		"Philosophy of Criminal Law":{
			"Punishment":{},
			"Justification and Excuse":{},
			"Defenses":{},
			"Specific Crimes":{},
			"Criminal/Tort Distinction":{},
			"Philosophy of Criminal Law, Misc":{}}},
	"Philosophy of Private Law":{
			"Contracts":{},
			"Torts":{},
			"Property":{}},
	"Philosophy of Constitutional Law":{
			"Constitutionalism":{},
			"Constitutional Interpretation":{}},
	"Philosophy of International Law":{},
	"Philosophy of Evidence and Proof":{},
	"Philosophy of Other Areas of Law":{},
	"Philosophy of Law, Misc":{},
	"Social and Political Philosophy":{
		"Culture and Cultures":{
			"Cultural Cosmopolitanism":{},
			"Cultural Relativism":{},
			"Multiculturalism":{
				"Multiculturalism and Autonomy":{},
				"Multiculturalism and Feminism":{},
				"Multicultural Liberalism":{}},
			"Minorities":{
				"Affirmative Action":{},
				"Minority Rights":{},
				"Identity Politics":{},
				"Politics of Recognition":{}},
			"Cultural Pluralism":{}},
		"Equality":{
			"Affirmative Action":{},
			"Distributive Justice":{},
			"Egalitarianism":{
				"The Scope of Equality":{},
				"The Value of Equality":{},
				"Equality and Capabilities":{},
				"Equality and Responsibility":{},
				"The Leveling-Down Objection":{}},
			"Priority and Prioritarianism":{},
			"The Concept of Equality":{},
			"Varieties of Equality":{
				"Equality of Welfare":{},
				"Equality of Resources":{},
				"Equality of Opportunity":{}}}},
 	"Freedom and Liberty":{
		"Coercion":{},
		"Exploitation":{},
		"Free Will":{},
		"Autonomy":{},
		"Specific Freedoms":{
			"Freedom of Assembly":{},
			"Freedom of Association":{},
			"Freedom of Movement":{},
			"Freedom of Religion":{},
			"Freedom of Speech":{},
			"Freedom of Thought":{}},
		"Positive and Negative Freedom":{},
		"Philosophy of Gender, Race, and Sexuality":{},
		"Government and Democracy":{
			"Democracy":{
				"Civic Virtue":{},
				"Civil Society":{},
				"Conceptions of Democracy":{},
				"Deliberative Democracy":{},
				"Democratic Authority":{},
				"Justification of Democracy":{},
				"Participatory Democracy":{},
				"Representative Democracy":{}},
			"Government":{
				"Authoritarianism":{},
				"Constitutional Law":{},
				"Paternalism":{},
				"Political Legitimacy":{}},
			"Political Authority":{
				"Anarchism":{},
				"Associative Obligations":{},
				"Consensus and Political Authority":{},
				"Consent and Political Authority":{},
				"Democratic Authority":{},
				"Instrumentalism about Political Authority":{},
				"Public Justification":{},
				"Political Legitimacy":{}},
			"Social Contract":{
				"Contractarianism about Political Authority":{},
				"Contractualism about Political Authority":{},
				"Moral Contractualism and Contractarianism":{}},
			"Social Choice":{
				"Arrow's Theorem":{},
				"Concdorcet's Paradox":{},
				"Judgment Aggregation":{},
				"Social Choice, Misc":{}
			}
		},
		"International Philosophy":{
			"Cosmopolitanism":{
				"Cultural Cosmpolitanism":{},
				"Economic Cosmpolitanism":{},
				"Moral Cosmopolitanism":{},
				"Political Cosmopolitanism":{}
			},
			"Globalization":{},
			"Imperialism":{},
			"Intervention":{},
			"International Ethics":{},
			"Global Justice":{},
			"Global Governance":{},
			"International Law":{},
			"Realism and Neo-Realism":{}
		},
		"Justice":{
			"Criminal Justice":{},
			"Distributive Justice":{
				"Desert and Distributive Justice":{},
				"The Difference Principle":{},
				"The Original Position":{},
				"Egalitarianism":{},
				"Global Justice":{},
				"Libertarian Critique of Distributive Justice":{},
				"Prioritarianism":{},
				"Welfare":{}
			},
			"Environmental Justice":{},
			"Global Justice":{},
			"Health Care Justice":{},
			"International Justice":{},
			"The Nature of Justice":{}
		},
		"Philosophy of Social Science":{},
		"Political Theory":{},
		"Political Views":{
			"Anarchism":{},
			"Communitarianism":{},
			"Conservatism":{},
			"Constructivism":{},
			"Liberalism":{
				"Liberalism and Liberty":{},
				"Classical Liberalism":{},
				"New Liberalism":{},
				"Political Liberalism":{},
				"Liberalism and Value":{},
				"The Scope of Liberalism":{}
			},
			"Libertarianism":{},
			"Perfectionism":{},
			"Republicanism":{},
			"Socialism and Marxism":{}
		},
		"Rights":{
			"Civil and Political Rights":{
				"Freedom of Speech":{},
				"Freedom of Thought":{},
				"Freedom of Assembly":{},
				"Freedom of Association":{},
				"Freedom of Movement":{}},
			"The Concept of Rights":{
				"Hohfeldian Analysis":{}},
			"The Basis of Rights":{
				"Contractarian And Consent Theories":{},
				"Will Versus Interest Theories":{},
				"Rights and Utilitarianism":{}},
			"Aspects of Rights":{
				"Conflicts Among Rights":{},
				"Criticisms of Rights":{},
				"Rights and Equality":{},
				"Rights and Freedom":{}},
			"Specific Rights, Misc":{
				"Childrens Rights":{},
				"Environmental Rights":{},
				"Minority and Group Rights":{},
				"Natural Rights":{},
				"Right to Employment":{},
				"Trade Union Rights":{},
				"Health Care Rights":{}},
			"Human Rights":{
				"Human Rights Law":{},
				"Human Rights Treaties":{}},
			"Property Rights":{
				"Original Appropriation":{},
				"Externalities":{}}
			},
		"Social and Political Philosophy, Misc":{
			"Exploitation":{},
			"Political Concepts":{},
			"Political Obligation":{},
			"The Political Role of Philosophy":{},
			"Property":{},
			"Markets":{}
		},
		"States and Nations":{
			"Political Authority":{},
			"Civil War":{},
			"Immigration":{},
			"Intervention":{},
			"Nationalism":{},
			"Patriotism":{},
			"Political Authority":{},
			"Political Power":{},
			"Revolution":{},
			"Secession":{},
			"Sovereignty":{},
			"Statehood":{}
		},
		"War and Violence":{
			"Violence":{
				"Genocide":{},
				"Gun Control":{},
				"Murder":{},
				"Rape":{},
				"Terrorism":{},
				"Torture":{},
				"Violence, Misc":{}
			},
			"War":{
				"Civil War":{},
				"Conduct of War":{},
				"Deterrence":{},
				"Ethics and Justification of War":{},
				"Just War Theory":{},
				"Nature of War":{},
				"Nuclear War":{},
				"Pacifism":{},
				"Purpose of War":{},
				"War Crimes":{}
			}
		}
	},
	"Value Theory, Misc":{
		"Normativity":{
			"Aesthetic Normativity":{},
			"Epistemic Normativity":{},
			"Moral Normativity":{},
			"Normativity of Meaning and Content":{},
			"Normativity of Practical Reason":{},
			"Normativity and Naturalism":{},
			"Normativity, Misc":{}},
		"Value":{
			"Aesthetic Value":{},
			"Axiology":{},
			"Epistemic Value":{},
			"Environmental Value":{},
			"Intrinsic Value":{},
			"Moral Value":{},
			"The Fact-Value Distinction":{},
			"Value, Misc":{}},
		"Value Theory, Misc":{}
	}
},
"Science, Logic, and Mathematics":{
	"Logic and Philosophy of Logic":{
		"Logics":{
			"Classical Logic":{
				"Aristotelian Logic":{},
				"Propositional Logic":{},
				"Predicate Logic":{}},
			"Deontic Logic":{},
			"Epistemic Logics":{
				"Doxastic and Epistemic Logic":{},
				"Inductive Logic":{},
				"Nonmonotonic Logic":{}},
			"Higher-Order Logics":{
				"Second-Order Logic":{},
				"Higher-Order Logics, Misc":{}},
			"Modal and Intensional Logic":{
				"Intensional Modal Logic":{},
				"Modal Logic":{},
				"Provability Logics":{},
				"Quantified Modal Logic":{},
				"Semantics for Modal Logic":{}},
			"Nonclassical Logics":{
				"Fuzzy Logics":{},
				"Infinitary Logics":{},
				"Intuitionistic Logic":{},
				"Many-Valued Logics":{},
				"Paraconsistent Logics":{},
				"Quantum Logic":{},
				"Relevance Logics":{},
				"Substructural Logics":{}},
			"Temporal Logic":{},
			"Logics, Misc":{
				"Logical Pluralism":{}
			}
		},
		"Logical Consequence and Entailment":{},
		"Logical Expressions":{
			"Logical Constants":{},
			"Logical Connectives":{},
			"Quantifiers":{},
			"Variables":{}},
		"Logical Paradoxes":{
			"Sorites Paradox":{},
			"Liar Paradox":{},
			"Russell's Paradox":{}},
		"Logical Semantics and Logical Truth":{},
		"Model Theory and Proof Theory":{},
		"Philosophy of Logic, Misc":{
			"Dialetheism":{},
			"Epistemology of Logic":{},
			"Informal Logic":{},
			"Logical Pluralism":{},
			"Logic in Philosophy":{}
		}
	},
	"Philosophy of Biology":{
		"Developmental Biology":{
			"Developmental Constraints":{},
			"Developmental Modularity":{},
			"Developmental Systems Theory":{},
			"Epigenetic Inheritance":{},
			"Evolutionary Developmental Biology":{},
			"Genetic Program":{},
			"Innateness":{},
			"Nature and Nurture":{},
			"Process Structuralism":{}},
		"Ecology and Conservation Biology":{
			"Biodiversity":{},
			"Conservation Biology, Misc":{},
			"Conservation Ethics":{},
			"Deep Ecology":{},
			"Ecology, Misc":{},
			"Ecosystems":{},
			"Population Ecology":{},
			"Prioritization":{},
			"Reduction in Ecology":{},
			"Social Ecology":{}},
		"Evolutionary Biology":{
			"Anti-Darwinist Approaches":{
				"Evolution and Creationism":{},
				"Intelligent Design":{},
				"Punctuated Equilibrium":{},
				"Process Structuralism":{}},
			"Levels and Units of Selection":{
				"Group Selection":{},
				"Gene Selection":{},
				"The Selfish Gene":{},
				"Organismic Selection":{},
				"Levels of Selection, Misc":{},
				"Units of Selection, Misc":{}},
			"Evolution of Phenomena":{
				"Evolution of Altruism":{},
				"Evolution of Cognition":{},
				"Evolution of Complexity":{},
				"Evolution of Consciousness":{},
				"Evolution of Culture":{},
				"Evolution of Language":{},
				"Evolution of Morality":{},
				"Sociobiology":{}},
			"Mechanisms of Evolution":{
				"Drift":{},
				"Epigenetic Inheritance":{},
				"Exaptation":{},
				"Heritability":{},
				"Natural Selection":{},
				"Niche Construction":{},
				"Speciation":{}},
			"Evolutionary Biology, Misc":{
				"Adaptationism":{},
				"Darwinism":{},
				"Epistemology of Evolution":{},
				"Evolutionary Progress":{},
				"Fitness":{},
				"Functions":{},
				"Optimality":{}
			}
		},
		"Genetics and Molecular Biology":{
			"Genetics":{
				"Classical Genetics":{},
				"Classical and Molecular Genetics":{},
				"Genetics, Misc":{},
				"Genotypes and Phenotypes":{},
				"Molecular Genetics":{},
				"Population Genetics":{},
				"Reduction in Genetics":{}},
			"Genes":{
				"Defining Genes":{},
				"Gene Concepts":{},
				"Genome Project":{},
				"Genetic Determinism":{},
				"Genetic Information":{},
				"Genetic Program":{},
				"Selfish Gene":{}},
			"Molecular Biology, Misc":{}},
		"Philosophy of Biology, Misc":{
			"Artificial Life":{},
			"Biological Information":{},
			"Biological Modeling":{},
			"Causation in Biology":{},
			"Complexity":{},
			"Explanation in Biology":{},
			"Life":{},
			"Philosophy of Biology, Misc":{},
			"Vitalism":{}},
		"Systematic Biology":{
			"Homology":{},
			"Biological Natural Kinds":{},
			"Organisms":{},
			"Populations":{},
			"Species":{
				"Essentialism about Species":{},
				"Phylogenetic Inference":{},
				"Species Concepts":{},
				"The Metaphysics of Species":{}
			}
		}
	},
	"Philosophy of Cognitive Science":{
		"Philosophy of Artificial Intelligence":{
			"Can Machines Think?":{
				"The Turing Test":{},
				"Godelian arguments":{},
				"The Chinese Room":{},
				"Machine Consciousness":{},
				"Machine Mentality, Misc":{}},
			"Computation and Representation":{
				"Symbols and Symbol Systems":{},
				"Computational Semantics":{},
				"Implicit/Explicit Rules and Representations":{},
				"AI without Representation?":{},
				"Representation in Connectionism":{},
				"Subsymbolic Computation":{},
				"Computation and Representation, Misc":{}},
			"Philosophy of Connectionism":{
				"Connectionism and Compositionality":{},
				"Representation in Connectionism":{},
				"Connectionism and Eliminativism":{},
				"The Connectionist/Classical Debate":{},
				"Subsymbolic Computation":{},
				"Philosophy of Connectionism, Misc":{},
				"Philosophy of Connectionism, Foundational Empirical Issues":{}},
			"Special Topics in AI":{
				"Artificial Life":{},
				"Cybernetics":{},
				"Dynamical Systems":{},
				"The Nature of AI":{},
				"The Frame Problem":{},
				"AI Methodology":{},
				"Robotics":{}},
			"Computationalism":{
				"Computationalism in Cognitive Science":{},
				"Computation and Physical Systems":{}},
			"Philosophy of AI, Misc":{}
		},
		"Philosophy of Psychology":{
			"Movements in Psychology":{
				"Behaviorism":{},
				"Cognitivism":{},
				"Introspection and Introspectionism":{}},
			"Theory of Mind and Folk Psychology":{
				"The Nature of Folk Psychology":{},
				"The Theory Theory":{},
				"The Simulation Theory":{},
				"Theory of Mind, Misc":{},
				"Folk Concepts and Folk Intuitions":{}},
			"Issues in Psychology":{
				"Parapsychology":{},
				"Science of Perception":{},
				"Psychological Laws":{},
				"Psychological Explanation":{},
				"Reduction in Psychology and Neuroscience":{}},
			"Philosophy of Psychology, Misc":{}
		},
		"Philosophy of Neuroscience":{
			"Imaging and Localization":{},
			"Representation in Neuroscience":{},
			"Explanation in Neuroscience":{},
			"Reduction in Psychology and Neuroscience":{},
			"Interlevel Relations":{},
			"Neurophilosophy":{},
			"Philosophy of Neuroscience, Misc":{}},
		"Philosophy of Linguistics":{},
		"Philosophy of Psychiatry and Psychopathology":{
			"Delusions":{},
			"Schizophrenia":{},
			"Other Mental Disorders":{},
			"Mental Illness":{},
			"Psychotherapy and Psychoanalysis":{},
			"Philosophy of Psychiatry and Psychopathology, Misc":{}},
		"Philosophy of Cognitive Science, General":{
			"Nativism":{},
			"Modularity":{},
			"Evolution of Cognition":{},
			"Rationality and Cognitive Science":{},
			"Embodiment and Situated Cognition":{},
			"Animal Cognition":{},
			"Levels of Analysis":{},
			"Explanation in Cognitive Science":{},
			"Representation in Cognitive Science":{},
			"Computationalism in Cognitive Science":{},
			"Philosophy of Cognitive Science, Misc":{}},
		"Science of Consciousness":{
			"Consciousness and Neuroscience":{},
			"Visual Consciousness":{},
			"Consciousness and Psychology":{},
			"Unconscious and Conscious Processes":{},
			"Disorders and Syndromes of Consciousness":{},
			"States of Consciousness":{},
			"Consciousness and Physics":{},
			"Consciousness and Biology":{},
			"First-Person Approaches":{},
			"Consciousness and Science, Misc":{}
		}
	},
	"Philosophy of Computing and Information":{
		"Computation and Physical Systems":{
			"Analog and Digital Computation":{},
			"Computers":{},
			"Implementing Computations":{},
			"Noncomputable Processes":{},
			"Pancomputationalism":{},
			"Quantum Computation":{}},
		"Computer Ethics":{},
		"Computer Simulation and Virtual Reality":{
			"Simulation and Reality":{},
			"Are We in a Simulation?":{},
			"Virtual Reality":{}},
		"Philosophy of Artificial Intelligence":{},
		"Philosophy of Computation, Misc":{
			"Computers in Philosophy":{},
			"Computer Languages":{},
			"Databases":{},
			"The Internet":{},
			"Hypertext":{},
			"Programs":{},
			"Software":{},
			"Software Verification":{}},
		"Philosophy of Information":{
			"Concepts of Information":{},
			"The Information Economy":{},
			"The Infosphere":{},
			"Information Theory":{},
			"Information Ethics":{},
			"Physics of Information":{}},
		"Theory of Computation":{
			"The Church-Turing Thesis":{},
			"Algorithmic Complexity":{},
			"Computability":{},
			"Computational Complexity":{},
			"Theory of Computation, Misc":{}
		}
	},
	"Philosophy of Mathematics":{
		"Epistemology of Mathematics":{
			"Apriority in Mathematics":{},
			"Epistemology of Mathematics, Misc":{},
			"Mathematics and the Causal Theory of Knowledge":{},
			"Mathematical Intuition":{},
			"Mathematical Proof":{
				"Godel's Theorem":{},
				"Computer Proof":{},
				"Probabilistic Proof":{},
				"Undecidability":{},
				"Mathematical Proof, Misc":{}},
			"Revisability in Mathematics":{}},
		"Mathematical Objects":{
			"Fictionalism":{},
			"Indeterminacy":{},
			"Nominalism":{},
			"Platonism":{},
			"Structuralism":{},
			"Neo-Fregean Approaches":{},
			"Indispensability Arguments":{},
			"Numbers":{},
			"The Nature of Sets":{}},
		"Mathematical Truth":{
			"Analyticity in Mathematics":{},
			"Axiomatic Truth":{},
			"Objectivity Of Mathematics":{}},
		"Philosophy of Set Theory":{
			"The Nature of Sets":{
				"The Iterative Conception of Set":{},
				"Ontology of Sets":{}},
			"Axioms of Set Theory":{
				"Axiomatic Truth":{},
				"The Axiom of Choice":{},
				"The Axiom of Constructibility":{},
				"The Axiom of Determinacy":{},
				"The Axiom of Infinity":{},
				"New Axioms":{},
				"Independence Results":{}},
			"Cardinals and Ordinals":{
				"The Continuum Hypothesis":{},
				"Large Cardinals":{}},
			"Set Theory as a Foundation":{
				"Russell's Paradox":{},
				"Set Theory and Logicism":{},
				"Set-Theoretic Constructions":{}
			}
		},
		"Areas of Mathematics":{
			"Algebra":{},
			"Analysis":{},
			"Category Theory":{},
			"Geometry":{},
			"Logic":{},
			"Number Theory":{},
			"Topology":{}},
		"Theories of Mathematics":{
			"Logicism":{},
			"Formalism":{},
			"Intuitionism and Constructivism":{},
			"Predicativism":{},
			"Mathematical Naturalism":{}},
		"Philosophy of Mathematics, Misc":{
			"Explanation in Mathematics":{},
			"The Infinite":{},
			"The Application of Mathematics":{}
		}
	},
	"Philosophy of Physical Science":{
		"Complex Systems":{
			"Artificial Life":{},
			"Chaos":{},
			"Complexity":{},
			"Emergence":{},
			"Nonlinear Dynamics":{},
			"Systems Theory":{}},
		"Philosophy of Chemistry":{
			"Bonding":{},
			"Chemical Explanation":{},
			"Chemical Laws":{},
			"Chemical Substance":{},
			"Chemical Supervenience":{},
			"Chemical Synthesis":{},
			"Elements":{},
			"Molecular Structure":{},
			"Organic Chemistry":{},
			"Periodic Table":{},
			"Quantum Chemistry":{},
			"Realism in Chemistry":{},
			"Reduction in Chemistry":{},
			"Thermodynamics and Statistical Mechanics":{}},
		"Philosophy of Cosmology":{
			"The Early Universe":{
				"The Big Bang":{},
				"Inflation":{},
				"Origin of the Universe":{}},
			"Design and Observership":{
				"Anthropic Principle":{},
				"Fine-Tuning":{},
				"Multiple Universes":{},
				"Observation in Cosmology":{}},
			"Philosophy of Cosmology, Misc":{
				"Extraterrestial Life and Intelligence":{},
				"The Cosmological Argument":{},
				"Why is there Something?":{}}},
		"Philosophy of Earth Sciences":{},
		"Philosophy of Physics, Misc":{
			"Astrophysics":{},
			"Atomic and Molecular Physics":{},
			"Biophysics":{},
			"Condensed Matter Physics":{},
			"Classical Mechanics":{},
			"Electromagnetism":{},
			"Gauge Theories":{},
			"Particle Physics":{},
			"Solid State Physics":{},
			"String Theory":{},
			"Thermodynamics and Statistical Mechanics":{},
			"Symmetry in Physics":{}},
		"Philosophy of Physical Science, Misc":{},
		"Quantum Mechanics":{
			"Interpretation of Quantum Mechanics":{
				"Bohmian Interpretation":{},
				"Collapse Interpretations":{},
				"Copenhagen Interpretation":{},
				"Decoherence Interpretations":{},
				"Everett Interpretation":{},
				"Measurement Problem":{},
				"Modal Interpretations":{},
				"Probabilities in Quantum Mechanics":{},
				"Relational Interpretations":{},
				"Transactional Interpretation":{},
				"Interpretations of QM, Misc":{}},
			"Quantum Theories":{
				"Quantum Chromodynamics":{},
				"Quantum Chemistry":{},
				"Quantum Computation":{},
				"Quantum Electrodynamics":{},
				"Quantum Field Theory":{},
				"Quantum Gravity":{},
				"Quantum Logic":{}},
			"Quantum Nonlocality":{
				"Action at a Distance":{},
				"Bell's Theorem":{},
				"Einstein-Podolsky-Rosen":{},
				"Entanglement":{}},
			"Quantum Mechanics, Misc":{
				"Complementarity":{},
				"Quantum Determinism and Indeterminism":{},
				"Quantum Self-Observation":{},
				"Schrodinger's Cat":{},
				"Uncertainty Principle":{},
				"Wave-Particle Duality":{}}},
		"Spacetime and Relativity":{
			"Metaphysics of Spacetime":{
				"Absolute Space":{},
				"Causal Theories":{},
				"Conventionalism about Spacetime":{},
				"Relationism":{},
				"Substantivalism":{},
				"The Hole Argument":{}},
			"Special Relativity":{
				"Simultaneity":{},
				"The Twin Paradox":{}},
			"General Relativity":{},
			"Physics of Time":{}}},
	"Philosophy of Probability":{
		"Confirmation and Induction":{},
		"Decision Theory":{},
		"Interpretation of Probability":{
			"Chance and Objective Probability":{},
			"Classical Probability":{},
			"Frequentism":{},
			"Logical Probability":{},
			"Propensities":{},
			"Subjective Probability":{},
			"Interpretion of Probability, Misc":{}},
		"Mathematics of Probability":{
			"Axioms of Probability":{},
			"Infinitesimals and Probability":{},
			"Mathematics of Probability, Misc":{}},
		"Probabilistic Reasoning":{
			"Bayesian Reasoning":{
				"Bayesian Reasoning, Misc":{},
				"Conditionalization":{},
				"Prior Probabilities":{},
				"The Problem of Old Evidence":{}},
			"Probabilistic Principles":{
				"Conditionalization":{},
				"Indifference Principles":{},
				"Scoring Rules":{},
				"The Principal Principle":{},
				"The Reflection Principle":{},
				"Updating Principles":{}},
			"Probabilistic Frameworks":{
				"Bayesian Reasoning":{},
				"Causal Modeling":{},
				"Dempster-Shafer Theory":{},
				"Plausibility Theory":{},
				"Probability and AI":{}},
			"Probabilistic Puzzles":{
				"Monty Hall":{},
				"New Riddle of Induction":{},
				"Paradox of Confirmation":{},
				"Sleeping Beauty":{}},
			"Subjective Probability":{
				"Betting Interpretations and Dutch Books":{},
				"Conditional Probability":{},
				"Degrees of Belief":{},
				"Imprecise Credences":{}}},
		"Philosophy of Statistics":{},
		"Philosophy of Probability, Misc":{}},
	"Philosophy of Science, General":{
		"Confirmation and Induction":{
			"Evidence":{},
			"Confirmation":{
				"Bayesianism":{},
				"Confirmation Holism":{},
				"Varieties of Confirmation":{},
				"The Paradox of Confirmation":{},
				"The Quine-Duhem Thesis":{}},
			"Induction":{
				"Induction and Other Minds":{},
				"Induction, Misc":{},
				"Inductive Logic":{},
				"Inductive Reasoning":{},
				"Inductive Skepticism":{},
				"Justification of Induction":{},
				"The New Riddle of Induction":{}},
			"Probabilistic Reasoning":{}},
		"Explanation":{
			"Causal Accounts of Explanation":{},
			"Deductive-Nomological Explanation":{},
			"Unification Accounts of Explanation":{},
			"Mechanisms in Explanation":{},
			"Narrative Explanation":{},
			"Statistical Explanation":{},
			"Pragmatics and Explanation":{},
			"Inference to the Best Explanation":{}},
		"History of Science":{},
		"Laws of Nature":{},
		"Philosophy of Science, Misc":{
			"Demarcation of Science":{},
			"Nature of Science":{},
			"Pseudoscience":{}},
		"Reduction and Interlevel Relations":{
			"Reduction":{
				"Nonreductive Materialism":{},
				"Reductionism":{},
				"Reduction and Multiple Realizability":{},
				"Reduction in Chemistry":{},
				"Reduction in Ecology":{},
				"Reduction in Genetics":{},
				"Reduction in Psychology and Neuroscience":{},
				"Reduction in Social Sciences":{},
				"Reduction, Misc":{},
				"Reductive Explanation":{},
				"Theory Reduction":{}},
			"Other Intertheoretic Relations":{},
			"Emergence":{},
			"Interlevel Metaphysics":{},
			"Metaphysics of Mind":{},
			"Physicalism":{},
			"Supervenience":{}},
		"Scientific Change":{
			"Convergent Realism":{},
			"Evolutionary Epistemology":{},
			"Incommensurability of Theories":{},
			"Research Programs":{},
			"Scientific Change, Misc":{},
			"Scientific Progress":{},
			"Scientific Revolutions":{},
			"Theory Change":{}},
		"Scientific Language":{
			"Cognitive Significance in Science":{},
			"Conceptual Change and Meaning Change":{},
			"Incommensurability":{},
			"Operationalism":{},
			"Ramsey Sentences":{},
			"Reference in Science":{}},
		"Scientific Practice":{
			"Experimentation":{},
			"Measurement":{},
			"Observation":{
				"Observables":{},
				"The Observation-Theory Distinction":{}},
			"Prediction":{},
			"Scientific Discovery":{},
			"Scientific Instruments":{},
			"Simulation":{},
			"Thought Experiments":{}},
		"Scientific Realism":{
			"Varieties of Scientific Realism":{
				"Convergent Realism":{},
				"Entity Realism":{},
				"Structural Realism":{}},
			"Alternatives to Scientific Realism":{
				"Constructive Empiricism":{},
				"Conventionalism":{},
				"Natural Ontological Attitude":{},
				"Scientific Fictionalism":{},
				"Social Constructionism":{},
				"Instrumentalism":{}},
			"Arguments for and Against Scientific Realism":{
				"Convergence":{},
				"Inference to the Best Explanation":{},
				"Novel Predictions":{},
				"The Observation-Theory Distinction":{},
				"Underdetermination of Theory by Data":{},
				"Historical Arguments Against Scientific Realism":{},
				"The Miracle Argument for Scientific Realism":{}},
			"Truth and Verisimilitude":{
				"Scientific Truth":{},
				"Verisimilitude":{}},
			"Scientific Realism, Misc":{}},
		"Sociology of Science":{},
		"Theories":{
			"The Nature of Theories":{
				"The Received View of Theories":{},
				"Research Programs":{},
				"Semantic View of Theories":{}},
			"Theoretical Virtues":{
				"Aesthetic Virtues in Science":{},
				"Conservatism":{},
				"Falsifiability":{},
				"Nonempirical Virtues":{},
				"Simplicity and Parsimony":{}},
			"Underdetermination of Theory by Data":{
				"Empirically Equivalent Theories":{},
				"Nonempirical Virtues":{},
				"Underdetermination of Theory by Data, Misc":{}},
			"Models and Idealization":{
				"Analogy in Science":{},
				"Approximation":{},
				"Idealization":{},
				"Models":{},
				"Semantic View of Theories":{}
			}
		}
	},
	"Philosophy of Social Science":{
		"Philosophy of Anthropology":{},
		"Philosophy of Economics":{},
		"Philosophy of Education":{},
		"Philosophy of Geography":{},
		"Philosophy of History":{},
		"Philosophy of Law":{},
		"Philosophy of Sociology":{},
		"Philosophy of Social Science, Misc":{
			"Functional Explanation":{},
			"Holism in Social Sciences":{},
			"Individualism in Social Sciences":{},
			"Objectivity and Value in Social Science":{},
			"Rational Choice Theory":{},
			"Reduction in Social Sciences":{},
			"Realism about Social Facts":{}
		}
	}
},
"History of Western Philosophy":{
	"Ancient Greek Philosophy":{
		"Classical Greek Philosophy":{
			"Aristotle":{},
			"Classical Greek Philosophers, Misc":{},
			"Plato":{},
			"Socrates":{}},
		"Hellenistic Philosophy":{
			"Stoics":{},
			"Epicureans":{},
			"Neoplatonists":{},
			"Academic Skeptics":{},
			"Pyrrhonists":{},
			"Hellenistic Philosophy, Misc":{}},
		"Pre-Socratic Philosophy":{
			"Milesians":{},
			"Pythagoreans":{},
			"Eleatics":{},
			"Pluralists":{},
			"Atomists":{},
			"Sophists":{},
			"Pre-Socratic Philosophy, Misc":{}},
		"Ancient Greek Philosophy, Misc":{}},
	"Medieval and Renaissance Philosophy":{
		"Pre-1000 Medieval Philosophy":{
			"Augustine":{},
			"Boethius":{}},
		"11th/12th Century":{
			"Abelard":{},
			"Anselm":{},
			"Roger Bacon":{}},
		"13th/14th Century":{
			"Aquinas":{},
			"Buridan":{},
			"Ockham":{},
			"Scotus":{}},
		"15th/16th Century":{
			"Erasmus":{},
			"Machiavelli":{}},
		"Medieval and Renaissance Philosophy, Misc":{}},
	"17th/18th Century Philosophy":{
		"17th/18th Century British Philosophy":{
			"Bentham":{},
			"Berkeley":{},
			"Hobbes":{},
			"Hume":{},
			"Hutcheson":{},
			"Locke":{},
			"Newton":{},
			"Reid":{},
			"Adam Smith":{}},
		"17th/18th Century French Philosophy":{
			"Descartes":{},
			"Malebranche":{},
			"Pascal":{},
			"Rousseau":{}},
		"17/18th Century German Philosophy":{
			"Fichte":{},
			"Leibniz":{},
			"Kant":{}},
		"17th/18th Century Philosophy, Misc":{
			"Spinoza":{}}},
	"19th Century Philosophy":{
		"19th Century American Philosophy":{
			"Dewey":{},
			"James":{},
			"Mead":{},
			"Peirce":{},
			"Royce":{}},
		"19th Century Austrian Philosophy":{
			"Brentano":{},
			"Freud":{},
			"Mach":{},
			"Meinong":{}},
		"19th Century British Philosophy":{
			"Bentham":{},
			"Bradley":{},
			"Mill":{},
			"Sidgwick":{}},
		"19th Century German Philosophy":{
			"Fichte":{},
			"Frege":{},
			"Hegel":{},
			"Husserl":{},
			"Marx":{},
			"Nietzsche":{},
			"Schelling":{},
			"Schopenhauer":{}},
		"Misc":{
			"Kierkegaard":{}},
		"19th Century Philosophy, Misc":{}},
	"20th Century Philosophy":{
		"20th Century Analytic Philosophy":{
			"Anscombe":{},
			"Austin":{},
			"Ayer":{},
			"Carnap":{},
			"Chisholm":{},
			"David Lewis":{},
			"Davidson":{},
			"Frege":{},
			"Goodman":{},
			"Kuhn":{},
			"Moore":{},
			"Popper":{},
			"Quine":{},
			"Rawls":{},
			"Rorty":{},
			"Russell":{},
			"Ryle":{},
			"Sellars":{},
			"Strawson":{},
			"Tarski":{},
			"Wittgenstein":{}},
		"20th Century Continental Philosophy":{
			"Adorno":{},
			"Arendt":{},
			"Bergson":{},
			"De Beauvoir":{},
			"Deleuze":{},
			"Derrida":{},
			"Foucault":{},
			"Gadamer":{},
			"Habermas":{},
			"Heidegger":{},
			"Husserl":{},
			"Irigaray":{},
			"Lacan":{},
			"Levinas":{},
			"Lyotard":{},
			"Merleau-Ponty":{},
			"Ricoeur":{},
			"Sartre":{}},
		"20th Century Philosophy, Misc":{
			"Collingwood":{},
			"Dewey":{},
			"Freud":{},
			"James":{},
			"Mead":{},
			"Meinong":{},
			"Royce":{},
			"Santayana":{},
			"Whitehead":{}}},
	"History of Western Philosophy, Misc":{}}}
